version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: truongclone232_ettshop_backend
    image: truongclone232/ettshop_backend:v1.0.0
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: truongclone232_ettshop_frontend
    image: truongclone232/ettshop_frontend:v1.0.0
    ports:
      - "3000:3000"

  ollama:
    image: truongclone232/ollama:v1.0.0
    container_name: truongclone232_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
